@beginURL = http://localhost:5031

GET {{beginURL}}/api/locations/

###
GET {{beginURL}}/api/lockers/

###
GET {{beginURL}}/api/lockers/30

###
GET {{beginURL}}/api/lockers/user/30

###
POST {{beginURL}}/api/lockers
Content-Type: application/json

{
  "ID": 0,
  "Number": "TTT011111",
  "LocationID": 113,
  "StudentID": null,
  "Status": 0
}

###

GET {{beginURL}}/api/students

###

POST {{beginURL}}/api/locations
Content-Type: application/json

{
  "ID": 0,
  "Name": "hall t",
  "Prefix": "t",
  "Description": null,
  "LockerCount": 10,
  "LockersPerColumn": 5
}