@beginURL = http://localhost:5031

GET {{beginURL}}/api/locations/

###
GET {{beginURL}}/api/lockers/

###
GET {{beginURL}}/api/lockers/30

###
GET {{beginURL}}/api/lockers/user/30

###
PUT {{beginURL}}/api/lockers/46
Content-Type: application/json

{
  "ID": 46,
  "Number": "L046",
  "LocationID": 3,
  "StudentID": null,
  "Status": 2,
  "Location": {
    "ID": 2,
    "Name": "Science Wing",
    "Description": "Lockers in the science building"
  }
}