-- Seed Locations
INSERT INTO Locations (Name, Description) VALUES
('Main Hall', 'Lockers near the main entrance'),
('Science Wing', 'Lockers in the science building'),
('Library', 'Lockers near the library'),
('Gym', 'Lockers in the gym area');

-- Seed Students
INSERT INTO Students (Name, LastName, Email, Class) VALUES
('Emma', 'Johnson', 'emma.johnson@school.com', '3B'),
('Liam', 'Williams', 'liam.williams@school.com', '2A'),
('Olivia', 'Brown', 'olivia.brown@school.com', '5C'),
('Noah', 'Jones', 'noah.jones@school.com', '1D'),
('Ava', 'Garcia', 'ava.garcia@school.com', '4A'),
('Elijah', 'Miller', 'elijah.miller@school.com', '6B'),
('Sophia', 'Davis', 'sophia.davis@school.com', '2C'),
('Mason', 'Martinez', 'mason.martinez@school.com', '3A'),
('Isabella', 'Rodriguez', 'isabella.rodriguez@school.com', '1B'),
( 'Lucas', 'Hernandez', 'lucas.hernandez@school.com', '5D'),
( 'Mia', 'Lopez', 'mia.lopez@school.com', '4C'),
( 'Logan', 'Gonzalez', 'logan.gonzalez@school.com', '2B'),
( 'Charlotte', 'Wilson', 'charlotte.wilson@school.com', '6A'),
( 'Ethan', 'Anderson', 'ethan.anderson@school.com', '3D'),
( 'Amelia', 'Thomas', 'amelia.thomas@school.com', '1C'),
( 'James', 'Taylor', 'james.taylor@school.com', '5B'),
( 'Harper', 'Moore', 'harper.moore@school.com', '4D'),
( 'Benjamin', 'Jackson', 'benjamin.jackson@school.com', '2D'),
( 'Evelyn', 'Martin', 'evelyn.martin@school.com', '6C'),
( 'Henry', 'Lee', 'henry.lee@school.com', '3C'),
( 'Abigail', 'Perez', 'abigail.perez@school.com', '1A'),
( 'Sebastian', 'Thompson', 'sebastian.thompson@school.com', '5A'),
( 'Emily', 'White', 'emily.white@school.com', '4B'),
( 'Jack', 'Harris', 'jack.harris@school.com', '2A'),
( 'Elizabeth', 'Sanchez', 'elizabeth.sanchez@school.com', '6D'),
( 'Alexander', 'Clark', 'alexander.clark@school.com', '3B'),
( 'Sofia', 'Ramirez', 'sofia.ramirez@school.com', '1D'),
( 'Daniel', 'Lewis', 'daniel.lewis@school.com', '5C'),
( 'Avery', 'Robinson', 'avery.robinson@school.com', '4A'),
( 'Matthew', 'Walker', 'matthew.walker@school.com', '2C'),
( 'Ella', 'Young', 'ella.young@school.com', '6B'),
( 'Jackson', 'Allen', 'jackson.allen@school.com', '3A'),
( 'Scarlett', 'King', 'scarlett.king@school.com', '1B'),
( 'David', 'Wright', 'david.wright@school.com', '5D'),
( 'Grace', 'Scott', 'grace.scott@school.com', '4C'),
( 'Carter', 'Torres', 'carter.torres@school.com', '2B'),
( 'Chloe', 'Nguyen', 'chloe.nguyen@school.com', '6A'),
( 'Wyatt', 'Hill', 'wyatt.hill@school.com', '3D'),
( 'Penelope', 'Flores', 'penelope.flores@school.com', '1C'),
( 'Julian', 'Green', 'julian.green@school.com', '5B'),
( 'Layla', 'Adams', 'layla.adams@school.com', '4D'),
( 'Leo', 'Nelson', 'leo.nelson@school.com', '2D'),
( 'Victoria', 'Baker', 'victoria.baker@school.com', '6C'),
( 'Gabriel', 'Hall', 'gabriel.hall@school.com', '3C'),
( 'Lily', 'Rivera', 'lily.rivera@school.com', '1A');

-- Seed Lockers
INSERT INTO Lockers (Number, StudentID, LocationID, Status) VALUES
('L001', 1, 1, 1),
('L002', 2, 2, 1),
('L003', 3, 3, 1),
('L004', 4, 4, 1),
('L005', 5, 1, 1),
('L006', 6, 2, 1),
('L007', 7, 3, 1),
('L008', 8, 4, 1),
('L009', 9, 1, 1),
('L010', 10, 2, 1),
('L011', 11, 3, 1),
('L012', 12, 4, 1),
('L013', 13, 1, 1),
('L014', 14, 2, 1),
('L015', 15, 3, 1),
('L016', 16, 4, 1),
('L017', 17, 1, 1),
('L018', 18, 2, 1),
('L019', 19, 3, 1),
('L020', 20, 4, 1),
('L021', 21, 1, 1),
('L022', 22, 2, 1),
('L023', 23, 3, 1),
('L024', 24, 4, 1),
('L025', 25, 1, 1),
('L026', 26, 2, 1),
('L027', 27, 3, 1),
('L028', 28, 4, 1),
('L029', 29, 1, 1),
('L030', 30, 2, 1),
('L031', 31, 3, 1),
('L032', 32, 4, 1),
('L033', 33, 1, 1),
('L034', 34, 2, 1),
('L035', 35, 3, 1),
('L036', 36, 4, 1),
('L037', 37, 1, 1),
('L038', 38, 2, 1),
('L039', 39, 3, 1),
('L040', 40, 4, 1),
('L041', 41, 1, 1),
('L042', 42, 2, 1),
('L043', 43, 3, 1),
('L044', 44, 4, 1),
('L045', 45, 1, 1),
('L046', 1, 2, 0),
('L047', 2, 3, 0),
('L048', 3, 4, 0),
('L049', 4, 1, 0),
('L050', 5, 2, 0);